Making a Prediction model using Gradient Descent algorithm with pytorch  

In [ ]:
#Linear regression using pytorch inbuit-ins 
import torch.nn as nn
import numpy as np
import torch

In [11]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')
inputs= torch.from_numpy(inputs)
targets= torch.from_numpy(targets)

In [12]:
#Step 1: define TensorDataset and Dataloader 
from torch.utils.data import TensorDataset, DataLoader 
train_ds= TensorDataset(inputs, targets)
batch_size=5
train_dl=DataLoader(train_ds, batch_size , shuffle= True)

In [13]:
#step 2: define a model using nn.linear 
model= nn.Linear(3,2)#cuz It has 3 inputs and it gives 2 output, it makes weights and biases 
preds= model(inputs) #generate predictions
print(preds)

tensor([[ 57.1864, -15.8535],
        [ 76.8248, -25.3677],
        [ 72.7853, -43.0945],
        [ 67.2564,   6.7571],
        [ 69.7248, -38.9598],
        [ 57.6363, -15.0811],
        [ 77.3175, -25.3361],
        [ 73.7676, -43.0933],
        [ 66.8065,   5.9848],
        [ 69.7677, -39.7006],
        [ 57.6791, -15.8219],
        [ 77.2747, -24.5953],
        [ 72.2925, -43.1261],
        [ 67.2135,   7.4979],
        [ 69.2749, -39.7321]], grad_fn=<AddmmBackward0>)


In [23]:
#Step 3: Make a loss function 
import torch.nn.functional as F 
loss_fn= F.mse_loss
loss= loss_fn(model(inputs), targets)

In [24]:
#Step 4: optimizers
opt= torch.optim.SGD(model.parameters(), lr= 1e-5)
#Instead of manually manipulating weights and biases of our model, you can use build-in function torch.optim.SGD()

In [25]:
list(model.parameters()) #return all the weight and biases in our model 

[Parameter containing:
 tensor([[ 0.4698,  0.0199,  0.5126],
         [ 0.3710, -0.4013, -0.3698]], requires_grad=True),
 Parameter containing:
 tensor([-0.4816, -0.1504], requires_grad=True)]

In [45]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb, in train_dl:
            preds= model(xb)
            loss= loss_fn(preds, yb)
            loss.backward()
            opt.step()# update the parameters
            opt.zero_grad()
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [46]:
fit(5, model, loss_fn, opt, train_dl)

Epoch [1/5], Loss: 8.6644
Epoch [2/5], Loss: 11.2213
Epoch [3/5], Loss: 7.9318
Epoch [4/5], Loss: 14.2725
Epoch [5/5], Loss: 16.4757


In [47]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

As so you can see our model is finally performing better, and can predict with accuracy

In [50]:
preds

tensor([[ 57.1864, -15.8535],
        [ 76.8248, -25.3677],
        [ 72.7853, -43.0945],
        [ 67.2564,   6.7571],
        [ 69.7248, -38.9598],
        [ 57.6363, -15.0811],
        [ 77.3175, -25.3361],
        [ 73.7676, -43.0933],
        [ 66.8065,   5.9848],
        [ 69.7677, -39.7006],
        [ 57.6791, -15.8219],
        [ 77.2747, -24.5953],
        [ 72.2925, -43.1261],
        [ 67.2135,   7.4979],
        [ 69.2749, -39.7321]], grad_fn=<AddmmBackward0>)